### ISSUE TITLE
Publish in Maven repository?

### ISSUE THREAD

**Issue by peacekeeper** [simon-greatrix/rdf-urdna#2]
Are you planning to publish the .jar file in a Maven repository so people can easily use it in their own projects?

**Comment by simon-greatrix** [comment]
Yes.

**Comment by simon-greatrix** [comment]
So the plan is to publish the .jar file to Maven. This requires my employers to set up publishing from the io.setl domain. That's going to take a few days.

**Comment by peacekeeper** [comment]
Any update on publishing this to Maven?

**Comment by simon-greatrix** [comment]
This has now been published to maven central. See:

https://search.maven.org/search?q=a:rdf-urdna
