### ISSUE TITLE
Update to be compatible with titanium-json-ld 1.0.0 ?

### ISSUE THREAD

**Issue by peacekeeper** [simon-greatrix/rdf-urdna#3]
titanium-json-ld had a 1.0.0. release: https://github.com/filip26/titanium-json-ld/releases/tag/v1.0.0

Would it be possible to update rdf-urdna to use titanium-json-ld 1.0.0 and then release rdf-urdna again as well?

As far as I can tell, the updates should be relatively simple (some renamed packages).

**Comment by simon-greatrix** [comment]
That's a great idea. I will be doing that.

**Comment by simon-greatrix** [comment]
Updated to use latest library, and released to maven central.
