### ISSUE TITLE
JRE8 Artifact

### ISSUE THREAD

**Issue by filip26** [simon-greatrix/rdf-urdna#4]
Hi, Titanium has published `titanium-json-ld-jre8` artifact - [1.3.1 Release](https://github.com/filip26/titanium-json-ld/releases/tag/v1.3.1). Would you consider to publish JRE8 version of rdf-urdna?  Thank you.

**Comment by simon-greatrix** [comment]
I have released 1.2 of the library which is now compatible with JRE8 and uses the Titanium JRE-8 library.

It should show on maven central in an hour or so
