### ISSUE TITLE
 Dataset Poisoning

### ISSUE THREAD

**Issue by filip26** [simon-greatrix/rdf-urdna#6]
Do you plan to implement any of those techniques described in  [7.1 Dataset Poisoning](https://www.w3.org/TR/rdf-canon/#dataset-poisoning) to enable dataset poisoning protection? Thank you!

**Comment by simon-greatrix** [comment]
My recommendation is to ban blank nodes. If there are no blank nodes, the algorithm runs in linear time. If there are blank nodes it runs in O(n!) time, which is awful.

If you design your JSON-LD documents so there are no blank nodes, and validate this before canonicalization, your dataset cannot be poisoned.

**Comment by filip26** [comment]
@simon-greatrix good point, but what if you don't have the structure of the JSON-LD document under your control? ;)

**Comment by simon-greatrix** [comment]
I have added protection against dataset poisoning.
