### ISSUE TITLE
Implement RDF Dataset Canonicalization and provide EARL report

### ISSUE THREAD

**Issue by gkellogg** [simon-greatrix/rdf-urdna#7]
Your implementation likely meets all of the requirements set out in [RDF Dataset Canonicalization](https://w3.org/TR/rdf-canon); please considerer submitting an EARL report.

The implementation report at https://w3c.github.io/rdf-canon/reports/ for CR transition already has five compatible implementations, but we'd like to see reports from other major implementations, such as Jena. The implementation report includes instructions for formatting and submitting new reports.

The test suite can be found at https://w3c.github.io/rdf-canon/tests/.

**Comment by simon-greatrix** [comment]
Thanks for making me aware of this. The implementation passed all the tests except:

Test 60 - Java has built-in URI support, but not IRI support, and the IRI parsing fails in the titanium library I use for parsing RDF

Test 74 - I have not implemented code to detect poisonous inputs.

I will consider how best to address these two test cases.

**Comment by simon-greatrix** [comment]
I have created an EARL report for the library and created a pull request to merge it into the list of known implementations.
