### ISSUE TITLE
Please remove version 1.3 (?)

### ISSUE THREAD

**Issue by ParaSait** [simon-greatrix/rdf-urdna#9]
Hello,

We have recently updated our dependency on rdf-urdna to version 1.3. This update was resulting in issues and my conclusion was that there's a bug in this version.

However, as I was looking to report this issue here, I've noticed that the tag for version 1.3 (https://github.com/setl/rdf-urdna/tree/1.3) is presently not on the master branch, and this raised some suspicions. Was the intention to roll the release of this version back by resetting the master branch? If so, please remove the tag and make sure that the jar is unpublished from Maven, because those currently still exist.

If version 1.3 in its current state _is_ actually supposed to exist, then I'll report said bug in a separate issue. Please let me know.

Thanks!

**Comment by simon-greatrix** [comment]
Version 1.3 was published intentionally as it passed both the old tests and the new ones. The tag is on the wrong branch by mistake.

Please raise a bug report for the issue you found.

**Comment by ParaSait** [comment]
Hello, thanks for confirming.

I've dug a little deeper and the issue is on our end, actually. We had an exclusion on titanium-json-ld, but version 1.3 of rdf-urdna apparently requires titanium 1.4.0 to function correctly. So never mind about that bug report! ;)
